const giacoya = {
    titleArt: 'Mónica Mascolo',
    title: 'Mónica Mascolo',
    url: 'url(/img/monicamascolo.jpg)',
    urlPerfil: '/img/giacoya/179fotoautor.jpg',
    parrafoUno:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    parrafoDos:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    parrafoTres:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    parrafoCuatro:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    parrafoCinco: 'lorem lorem.',
    obraUno:'img/mascolo/Lejania.jpg',
    obraDos: 'img/mascolo/Movimiento_II.jpg', 
    obraTres:'img/mascolo/Multicolor.jpg',
    obraCuatro: 'img/mascolo/Multicolor_II.jpg',
    obraCinco:'img/mascolo/Tormenta_2.jpg',
    tituloObraUno:'Título: ',
    tamanoObraUno: 'Tamaño:',
    tecnicaObraUno:'Técnica:',
    anoObraUno:'Año: ',
    tituloObraDos:'Título:',
    tamanoObraDos: 'Tamaño: ',
    tecnicaObraDos:'Técnica: ',
    anoObraDos:'Año: ',
    tituloObraTres:'Título: ',
    tamanoObraTres: 'Tamaño: ',
    tecnicaObraTres:'Técnica: ',
    anoObraTres:'Año:',
    enlaceUno:'/lejania',
    enlaceDos:'/movimientoII',
    enlaceTres:'/multicolor',
    tituloObraCuatro:'Título: ',
    tamanoObraCuatro: 'Tamaño: ',
    tecnicaObraCuatro:'Técnica: ',
    anoObraCuatro:'Año:',
    enlaceCuatro:'/multicolorII',
    tituloObraCinco:'Título: ',
    tamanoObraCinco: 'Tamaño: ',
    tecnicaObraCinco:'Técnica: ',
    anoObraCinco:'Año:',
    enlaceCinco:'/tormentaII'
}

module.exports = giacoya